name: hw4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.0.0
  sqflite: ^2.2.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  provider: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
  - words/words.txt
  - images/login_bottom.png
  - images/main_top.png
  - images/main_bottom.png
  - images/signup_top.png
  - images/user.png
  - images/icons/signup.svg
  - images/icons/login.svg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
